/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.susmithasrimani.gocd.googleChat

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertEquals("Hello world.", classUnderTest.greeting)
    }
}
